name: compliance-checks

on:
  pull_request:
    branches: main

jobs:
  compliance-checks:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Set up Python 3.10
    - name: Python 3.10 setup
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Install Poetry
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2

    # Cache Poetry packages
    - name: Cache Poetry packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    # Install dependencies
    - name: Install packages
      run: poetry install

    # Debugging: Output the environment variables
    - name: Show environment variables
      run: env

    # Debugging: Output the entire last commit message
    - name: Show last commit message
      run: git log -n 1

    # Commit Sign-off
    - name: Commit Sign-off
      run: |
        echo "Checking commit for sign-off..."
        git log --format='%H %B' -n 1
        if ! git log --format='%H %B' -n 1 | grep 'Signed-off-by'; then
          echo "Error: Commit must be signed off"
          echo "Please use 'git commit -s' to sign off your commits."
          exit 1
        else
          echo "Commit is properly signed off."

    # Run gitlint on commit messages
    - name: Gitlint
      run: |
        pip install gitlint
        gitlint

    # Run security checks
    - name: Run security checks
      run: poetry run safety check
